OPTIONS(skip=1)
load data APPEND
 into table SAP_PRIN_UTI_IW28
 fields terminated by ";"
 TRAILING NULLCOLS
 ( AVVISO,
DATA_AVVISO,
DESCRIZIONE,
TIPO_AVVISO,
ORDINE,
DATA_CREAZIONE,
ORA_CREAZIONE,
STATO_UTENTE,
CENTRO_LAVRESP,
DIVPIANIFMANUT
   )