OPTIONS(skip=1)
load data APPEND
 into table SAP_ZWFM_SOSP_TOT
 fields terminated by ";"
 TRAILING NULLCOLS
 ( ORDINE,
NUMSOSP,
DT_INIZ_SOSP,
DT_FINE_SOSP,
CAUSALE,
DESCRIZIONE,
TIPO_OGGETTO,
OPERAZIONE
   )