OPTIONS(skip=1)
load data
 into table crm_erdk
 fields terminated by ";"
 TRAILING NULLCOLS
 ( OPBEL,DRUCKDAT,FAEDN,FAEDS,BUDAT,BLDAT,STOKZ,INTOPBEL,FICA_V,IMPORTO,DIVISA,TOTAL_AMNT_USE,PYMET,ZLSCH,NRZAS,PARTNER,VKONT,PORTION,ABRVORG,FORMKEY,FIKEY,TOBRELEASD,SIMULATED,INVOICED,ABWVK,ABWBL,ERGRD,LANGU,INVOICING_PARTY,ERDAT,AEDAT,BEGRU,LOEVM,VERART,STO_BUDAT,STO_OPBEL,ICREASON,MAZAE,EXBEL,MAZAE_ABS,PRINTLOCK,TAXDATE,CREATION_TIME,BILLING_PERIOD,OSB_GROUP,ZZ_LIMIT,ZZ_RATEIZZABILE,ZZ_COD_CIG,ZZ_DET_DIRIG,REVLOCK,SEPA_PRENOT,INVDOCNO )