OPTIONS(skip=1)
load data APPEND	
 into table SAP_IW29
 fields terminated by ";"
 TRAILING NULLCOLS
 ( AVVISO,
ORDINE,
TIPO_AVVISO,
DATA_AVVISO,
DIVISIONE,
DIVPIANIFMANUT,
DATA_CREAZIONE,
DATA_DI_RIFERIMENTO,
STATO_UTENTE
   )