OPTIONS(skip=1)
load data
 into table crm_erch
 fields terminated by ";"
  TRAILING NULLCOLS
 ( BELNR,BUKRS,SPARTE,GPARTNER,VKONT,VERTRAG,BEGABRPE,ENDABRPE,ABRDATS,ADATSOLL,PTERMTDAT,BELEGDAT,ABWVK,BELNRALT,STORNODAT,ABRVORG,HVORG,KOFIZ,SIMULATION,BELEGART,BERGRUND,BEGNACH,TOBRELEASD,ERDAT,AEDAT,ABRDATSU,ABRVORGU,N_INVSEP,MANBILLREL,BACKBI,PERENDBI,BEGEND,ENDOFBB,ENDOFPEB,SC_BELNR_H,SC_BELNR_N,ZUORDDAA,BILLINGRUNNO,SIMRUNID,ORIGDOC,MEM_OPBEL,MEM_BUDAT,EXBILLDOCNO,BCREASON,NINVOICE,NBILLREL,BASDYPER,ESTINBILL,ESTINBILLU,ESTINBILL_SAV,ESTINBILL_USAV,BILLING_PERIOD )