load data 
 into table	 TABLE_SR_E_CONTATTI_T
 fields terminated by ";"
 TRAILING NULLCOLS
 ( SOCIETA,
DATA_CREAZIONE_CI,
STATO_SISTEMA_CI,
STATO_UTENTE_CI,
ID_SR,
SR_DATA_ORA_CR,
TIPO_OPERAZIONE_COMM,
SR_SCHEMA_CATEGORIZZ,
SR_ID_CAT_LIV_1,
ID_CATEGORIZZAZIONE,
CANALE_DI_CONTATTO,
STATO_UTENTE_SR,
STATO_SISTEMA_SR,
SR_DATA_DECORRENZA,
ID_CONTATTO_OUTBOUND,
STATO_UTENTE_CO,
DATA_INVIO_CLIENTE,
CONTO_CONTR,
IMPIANTO,
DATA_PROTOCOLLO
   )