OPTIONS(skip=1)
load data APPEND
 into table SAP_IW69
 fields terminated by ";"
 TRAILING NULLCOLS
 ( TIPO_PRIORITA,
AVVISO,
ORDINE,
CAP,
LOCALITA,
VIA,
TESTO_CD_CAUSA,
TESTO_GRUPPO_CD_CAUSA,
DESCRIZIONE,
INIZIO_GUASTI,
ORA_INIZIO_GUASTO,
FINE_RICHIESTA,
ORA_FINE_RICHIESTA,
PRIORITA,
TESTO_PRIORITA,
AUTORE_AVVISO,
DATA_AVVISO,
DATA_CREAZIONE,
DIVISIONE,
CAUSA,
TESTO_CAUSA,
ORA_CREAZIONE,
NOME_LISTA,
SEDE_TECNICA 
   )