OPTIONS(skip=1)
load data
 into table SAP_ORDINI_COMP_UTI_IW38
 fields terminated by ";"
 TRAILING NULLCOLS
 ( ORDINE,
TIPO_ODL,
TAM,
OP_TESTO_BR,
DT_INI_CARD,
DT_FINE_CARD,
STATO_SISTEMA,
STATO_UTENTE,
AVVISO,
DIVPIANIFMANUT,
CENT_LAV_RESP
   )